apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory
  namespace: argocd
spec:
  project: default
  source:
    directory:
      exclude: '{*.sh,README.md}'
      include: '*.yaml'
      recurse: true
    path: k8s
    repoURL: https://github.com/malikhq/pod-commanders.git
    targetRevision: pod-commanders
  destination:
    namespace: assignment-1
    server: https://kubernetes.default.svc
  syncPolicy:

    syncOptions:
      # Resource Management Options
      - CreateNamespace=true     # Auto-create namespace if it doesn't exist
 